import os
from dotenv import load_dotenv

load_dotenv()

# Конфигурация бота
BOT_TOKEN = os.getenv('8400770070:AAFahEEaffeqcI0kcMwq5QVlv0Aur1GdbA8')
ADMIN_IDS = list(map(int, os.getenv('ADMIN_IDS', '').split(','))) if os.getenv('8050595279') else []

# Список приваток (ваши ссылки)
PRIVATE_LINKS = [
    "https://t.me/+ZuUNjg1bJ3xiOTIy",
    "https://t.me/+ud0gESAJTRpiNGY6",
    "https://t.me/+ImsOnVdV-wkzMzgy",
    "https://t.me/+GoHxJYZjVHM2OTU8",
    "https://t.me/+OwCjJcf8MLMzMDY0",
    "https://t.me/+7R5UlNBtS_ozMjI0",
    "https://t.me/+EXlBIikoHqY5NjM0",
    "https://t.me/+tB3ELsrzjXYxNTA8",
    "https://t.me/+XS93nu2kjkgwYzEy",
    "https://t.me/+jtrr7X3DGJAyMzUy",
    "https://t.me/+CLvBRlmQyKRmZWNi",
    "https://t.me/+vTldRbXSDx8yNzY6",
    "https://t.me/+qSvuUw3Xi0plMzVk",
    "https://t.me/+3hsRBgNQeSA1Zjc0",
    "https://t.me/+fun3xCBTTCphNDY6",
    "https://t.me/+_-ZMOq11be9lNWNi",
    "https://t.me/+h_4WC3Kovq1iZjM0",
    "https://t.me/+5tPlzYo9dINjMGQ6",
    "https://t.me/+l6yx3GDPfZs3MTcy",
    "https://t.me/+JfWKSCrUdEQ4YmRi",
    "https://t.me/+sGbKNtgrKzMzZWI0",
    "https://t.me/+y0rpo4bAM6JmODAy",
    "https://t.me/+GJS2mdhj5_JmYTBi",
    "https://t.me/+kpRNywup-tIyYzUy",
    "https://t.me/+Cim4j0KPWU0zZWJi",
    "https://t.me/+fsFDo_r5bBk0Yjk0",
    "https://t.me/+JMHlFI45ppw1ZDky",
    "https://t.me/+y4MMo2_f4DFmODNi",
    "https://t.me/+Su7A6bDH_L8xYTUy",
    "https://t.me/+uvzDdXuTeCU5NDRi",
    "https://t.me/+2JJdqT5zSa0zMGM0",
    "https://t.me/+C1S2zINTJ3ozYjc0",
    "https://t.me/+_JLaUwx6NiMzOGRi",
    "https://t.me/+t6dpNkkV2G4yZDli",
    "https://t.me/+EEwhazNzq5wzMjIy",
    "https://t.me/+DfyaUSyV4VU2NTZi",
    "https://t.me/+0uN0IYrraJswNmFk",
    "https://t.me/+xqJEiHkw-6FiNmJi",
    "https://t.me/+Oolh-X6pIhhlYTMy",
    "https://t.me/+cLkkkmIwXYk4Yzcy",
    "https://t.me/+HKiEUZGsqgNjZWQ8",
    "https://t.me/+3QbqycNNYFI0ZjU6",
    "https://t.me/+bt6iivf0tTtmNTE6",
    "https://t.me/+JaQQu47vhDI2NmQy",
    "https://t.me/+la195L2Vi6kwNGY6",
    "https://t.me/money_privat",
    "https://t.me/+2uZS1rkKYf0xYTQy",
    "https://t.me/+MWPACm-3LfcyNDhi",
    "https://t.me/+AX3nc3ccbsYzNDcy",
    "https://t.me/+pfwrCNbzufs4MmYy",
    "https://t.me/+N-lHnITBnQwzYTUy",
    "https://t.me/+7c_9zzglmB9kNDZi",
    "https://t.me/+HV7bkdPcGNlkZDNi",
    "https://t.me/+kDKSJf_URHswYjE6",
    "https://t.me/+x36tz_yivtw2OTUy",
    "https://t.me/+x93CpFyfzM0zMGI6",
    "https://t.me/+5mHBDz0uXNdjOTky",
    "https://t.me/+Dz8Wq0f49Yg0YzAy",
    "https://t.me/+buEisxeRtmoxODUy",
    "https://t.me/+iw-gfvvZ3X04YjFi",
    "https://t.me/+a_fPWKEtkPE5YTNi",
    "https://t.me/+H-bsbMa0E3UyNzRi",
    "https://t.me/+CBn7FoQOUrdiMzgy",
    "https://t.me/+_moLfabROh42OGIy",
    "https://t.me/+GtfCYQZLCZ9iNGRi",
    "https://t.me/+RJvv-yFVApIzMmIy",
    "https://t.me/+xKnujl_UcjsxMWRi",
    "https://t.me/+cEsoBqGD17czZmE6",
    "https://t.me/+8Dxa4EHjNE40NDhi",
    "https://t.me/+ZLwB_RuBkS1kNGUy",
    "https://t.me/+XqUQbp47ASFmZTUy",
    "https://t.me/+W66EI52nh-QxOGEy",
    "https://t.me/+Vdn3E1RebYA2YmRi",
    "https://t.me/+Ox0riWtd7QI3MGEy",
    "https://t.me/+Roy-4nD6wjQ2YjIy",
    "https://t.me/+VhgN5Zm9QNkxYjA6",
    "https://t.me/+ayK2q4U8emczNWUy",
]
